### ISSUE TITLE
Able to swing through Iron bars through cobweb [1.16.5]

### ISSUE THREAD

**Issue by Margineanu6542** [Exidex/SwingThroughGrass#20]
I was playing with this mod and I was killing a powerful mob and I decided to catch him in a tight area, next to that area there were iron bars behind a cobweb, and weirdly, I could attack through the cobweb and iron bars, with a sword only I could

**Comment by Exidex** [comment]
Fixed for 1.19 and 1.18

**Comment by NighthowlerStudios** [comment]
This bug also exists on any solid block behind a "swing through block".  it is an exploit that really should have been patched for all versions, not just the newest two.  just an fyi for any pack devs that are seeing this issue crop up in their own packs in the future since legacy development is refused.

**Comment by Exidex** [comment]
@Kaleidio Unfortunately I don't have much time available to work on it. But I accept pull requests so you are welcome to backport it for all versions.
